services:
  mariadb:
    image: mariadb:10.11
    container_name: event-management-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: EGVdS2WosyOwkDz
      MYSQL_USER: michelle
      MYSQL_PASSWORD: HN9gGhk3fCSyyKN
      MYSQL_DATABASE: event_db
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - event_db_data:/var/lib/mysql
volumes:
  event_db_data: